### ISSUE TITLE
지금 소스상으로는 JSONObject를 매번 새로 생성하는 것으로 보입니다.

### ISSUE THREAD

**Issue by reinhard31** [LeeJinOne/ChatProgram#1]
`@Override
	public void actionPerformed(ActionEvent e) {
		String msg = textField.getText();
		if(msg.equalsIgnoreCase("-exit")) { 
			JSONObject jsonObject = new JSONObject();

			jsonObject.put("userID", id);
			jsonObject.put("body", msg);

			String message = jsonObject.toJSONString();

			cb.sendMessage(message);
			try{
				cb.out.flush();
				cb.in.close();
				cb.out.close();
				cb.socket.close();
				/* Do I change code in 'try'? */
			} catch (IOException ie) {
				ie.printStackTrace();
			}
		  	System.out.println("Socket Connected : " + cb.socket.isConnected());
			System.out.println("Socket Closed : " + cb.socket.isClosed() + "\n");
			System.exit(0); // <=== **Delete this code**
		/* ================================================= */
		/* These are where I want to recode and do something */
		} else if (msg.equalsIgnoreCase("-reconnect")) {
			ClientBackground cb = new ClientBackground();
			cb.reconnect();
		/* ================================================= */
		/* ================================================= */
		} else {
			JSONObject jsonObject = new JSONObject();

			jsonObject.put("userID", id);
			jsonObject.put("body", msg);

			String message = jsonObject.toJSONString();

			cb.sendMessage(message);
		}
		textField.setText("");
	}`
	
stackoverflow에서 원하시는 내용은
-reconnect 할때 원래 사용하던 id로 서버쪽에 출력되는 로직 아닌가요?
JSONObject를 전역으로 빼고 ClientGui 가 종료되기 전까지는 
해당 JSONObject를 재사용 하는 방식으로 교체 하시는건 어떤지요?

stackoverflow에 올리신 질문이 정확하게 무엇인지 파악이 어렵네요

**Comment by LeeJinOne** [comment]
제가 생각했던 방식은 이러합니다.
시작은 Client가 GUI에 "-exit"를 입력하면 로그아웃 처리가 되면서 
서버가 HashMap에서 Client의 ID를 제거하게 됩니다.
그 후에 Client의 GUI는 종료되지 않고 계속 켜진 상태이며
서버로부터 메시지의 송,수신이 불가능한 상태가 됩니다.
그 후 Client가 GUI textField에 "-reconnect"를 입력하면 기존에 부여받았던 ID를
서버로 송신하고 서버가 그 ID값을 받아 DataOutputStream과 함께 HashMap(clientMap)에
다시 등록하여 서버와 Client가 메시지 송수신을 재개하는것 입니다.
즉 Client가 원래 사용하던 ID를  재사용하는 것입니다.

그런데 여기서 문제가 발생한게 소켓이 한번 닫혀버리면 새로 생성하지 않는 한
 다시 열 수 없다는 겁니다.

**Comment by reinhard31** [comment]
다시 생성하면 문제가 되는 부분이 있나요?
소켓을 닫게 되면 그 소켓 객체를 다시 재사용할 수 없게 설계 되어 있습니다.
핸드쉐이킹이 모두 종료되고 상호간에 GoodBye 신호를 인지 하게 되면
종료된 소켓은 다시 열 수 없습니다.

**Comment by reinhard31** [comment]
소스를 면밀히 검토하지는 못했지만
서버쪽 소켓은 항상 열어두고
클라이언트쪽에서 접속이 들어오게 되면
데이터 소켓을 새로 열어주어 할당 하는 방식을 사용하셔야 합니다.

**Comment by LeeJinOne** [comment]
제가 지식이 부족해서 말씀하신 방법대로 해놓은건지 아닌지 정확하게 모르겠습니다...

**Comment by reinhard31** [comment]
서버 소켓이 정상적으로 accept 되었을때
Receiver 쓰레드를 실행시키도록 소스 일부를 수정해보았습니다.

테스트를 할 수 없어 정확한 디버깅은 불가 하지만 도움이 되었으면 합니다.

**Comment by LeeJinOne** [comment]
감사합니다^^ 나머지는 제가 직접 해보겠습니다.
도움주셔서 정말 감사합니다!

**Comment by LeeJinOne** [comment]
수정해주신대로 코드 수정후 -reconnect 해봤는데
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException이 뜨네요...ㅠ
그 전에 -exit를 하게되면 SocketException이 일어납니다.

java.lang.NullPointerException 에서 오류 나는 부분은
ClientBackground.reconnect(ClientBackground.java:58)
ClientGUI.actionPerformed(ClientGUI.java:80) 입니다.

**Comment by LeeJinOne** [comment]
추가로 질문드리고 싶은게 있는데 JSONObject를 지역변수로 두고 메소드가 실행될때 마다 재생성하게 만들면 안좋은가요?

**Comment by reinhard31** [comment]
시간이 너무 지나 이미 해결 하셨으리라 생각됩니다만

ClientGui에 전역으로 선언한 id 변수에 
데이터를 넣어주는 부분은 어디인가요?

소스상으로는 getId 부분만 보이네요.

reconnect 호출시 클라이언트 GUI를 새로 생성하는데
id값이 null 이므로 발생하는 오류로 보이구요

-exit시 발생하는 SocketException은 어떤 에러인지요?
이미 열려있는 소켓을 다시 열려고 한다는 에러 또는 닫혀 있는 소켓을 재사용하려는 에러인지 구분을 할 수 있는 로그가 없어서 판단이 어렵네요.

**Comment by LeeJinOne** [comment]
아직 해결은 못했습니다.

ClientBackground 에서 readUTF로 서버에서 전송한 id값을 받고 getID(id)로 ClientGUI에도
id값을 넣어주게끔 작성했습니다.

![image](https://user-images.githubusercontent.com/29173428/30412565-598d6164-9953-11e7-9685-f10a841def2f.png)
-exit 시 에러 로그

![image](https://user-images.githubusercontent.com/29173428/30412590-7ab867a8-9953-11e7-8d03-6ee65199fef6.png)
-reconnect 시 에러 로그 입니다.

**Comment by reinhard31** [comment]
아직 해결 안되셨으면
혹시 프로젝트 전체 파일을 올려주실수 있나요?

**Comment by LeeJinOne** [comment]
현재 github에 올려놓은게 전부입니다.
